# Generated by Django 3.2 on 2022-07-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='spicy_level',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
