# Generated by Django 3.2 on 2022-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220525_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_spicy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
