# Generated by Django 3.2 on 2022-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'none'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=False, max_length=1),
        ),
    ]
