# Generated by Django 3.2 on 2022-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
