# Generated by Django 3.2 on 2022-06-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220612_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_pid',
        ),
    ]
